[package]
name = "prettyblk"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "2.0"
terminal_size = "0.2"
nix = { version = "0.27", features = ["fs"] }

[[bin]]
name = "pblk"
path = "src/main.rs"
